---
title: Framework for power analysis using simulation
author: R package build
date: '2021-03-16'
slug: []
categories: []
tags: []
type: ''
subtitle: ''
image: ''
draft: TRUE
---

```{r, eval = FALSE}
s_define <- function() {
  
  #--- data definition code ---#
  
  #--- end ---#
  
  return(list_of_defs) # list_of_defs is a list of simstudy data definitions
}

s_generate <- function(deflist, argsvec) {
  
  list2env(deflist, envir = environment())
  list2env(as.list(argsvec), envir = environment())
  
  #--- data generation code ---#
  
  #--- end ---#
  
  return(generated_data) #  generated_data is a data.table
}

s_model <- function(dd) {
  
  #--- model code ---#
  
  #--- end ---#
  
  return(model_results) # model_results is a data.table
}

s_single_rep <- function(argsvec) {
  
  list_of defs <- s_define()
  generated_data <- s_generate(list_of_defs, argsvec)
  model_results <- s_model(generated_data)
  
  return(model_results)
}

s_replicate <- function(argsvec, nsim) {
  
  model_results <- rbindlist(
    parallel::mclapply(
      X = 1 : nsim, 
      FUN = function(x) s_single_rep(argsvec), 
      mc.cores = 4)
  )
  
  #--- summary statistics code ---#
  
  #--- end ---#
  
  return(summary_stats) # summary_stats is a data.table
}
```

```{r, eval=FALSE}
#---- specify varying power-related parameters ---#

param_1 <- c(...)
param_2 <- c(...)
param_3 <- c(...)

argmat <- expand.grid(param_1, param_2, param_3)
args <- asplit(argmat, MARGIN = 1)

#--- run locally ---#

summary_stats <- rbindlist(lapply(args, function(a) s_replicate(a, nsim = 1000)))
```
