baseurl = "/"
DefaultContentLanguage = "en"
title = "ouR data generation"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "KSG"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Ruminations on data generating processes, R, and statistics"
  # logo = "img/avatar-icon.png"
  # favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Keith Goldfeld"
  email = "keith.goldfeld@nyumc.org"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # github = "username"
  # twitter = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "simstudy"
    url = "https://cran.r-project.org/web/packages/simstudy/index.html"
    weight = 2
    
[[menu.main]]
    name = "NYUSOM"
    url = "https://med.nyu.edu/pophealth/department-population-health"
    weight = 3
    
[[menu.main]]
    name = "Bio"
    url = "https://med.nyu.edu/faculty/keith-s-goldfeld"
    weight = 4
    
    


