---
title: "simstudy"
comments: false
---

Simulation using [`simstudy`](https://cran.r-project.org/web/packages/simstudy/index.html) has two primary steps. First, the user **defines** the data elements of a data set. Second, the user **generates** the data, using the definitions in the first step. Additional functionality exists to simulate observed or randomized **treatment assignment/exposures**, to generate **survival** data, to create **longitudinal/panel** data, to create **multi-level/hierarchical** data, to create datasets with **correlated variables** based on a specified covariance structure, to **merge** datasets, and to create data sets with **missing** data. More detail is provided at each of the links:

* [Data definition & generation](/page/define_and_gen/)
* [Treatment/exposure assignment](/page/treat_and_exposure/)
* [Survival data](/page/survival/)
* [Longitudinal data](/page/longitudinal/)
* [Clustered data](/page/clustered/)
* [Correlated data](/page/correlated/)
* [Missing data](/page/missing/)
