<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>When marginal and conditional logistic model estimates diverge</title>
  <meta property="og:title" content="When marginal and conditional logistic model estimates diverge" />
  <meta name="twitter:title" content="When marginal and conditional logistic model estimates diverge" />
  <meta name="description" content="Say we have an intervention that is assigned at a group or cluster level but the outcome is measured at an individual level (e.g. students in different schools, eyes on different individuals). And, say this outcome is binary; that is, something happens, or it doesn’t. (This is important, because none of this is true if the outcome is continuous and at close to normally distributed.) If we want to measure the effect of the intervention - perhaps the risk difference, risk ratio, or odds ratio - it can really matter if we are interested in the marginal effect or the conditional effect, because there is a good chance they won’t be the same.">
  <meta property="og:description" content="Say we have an intervention that is assigned at a group or cluster level but the outcome is measured at an individual level (e.g. students in different schools, eyes on different individuals). And, say this outcome is binary; that is, something happens, or it doesn’t. (This is important, because none of this is true if the outcome is continuous and at close to normally distributed.) If we want to measure the effect of the intervention - perhaps the risk difference, risk ratio, or odds ratio - it can really matter if we are interested in the marginal effect or the conditional effect, because there is a good chance they won’t be the same.">
  <meta name="twitter:description" content="Say we have an intervention that is assigned at a group or cluster level but the outcome is measured at an individual level (e.g. students in different schools, eyes on different individuals). And, …">
  <meta name="author" content="Keith Goldfeld"/>
  <meta name="twitter:card" content="summary" />
  <meta property="og:url" content="/post/marginal-v-conditional/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="ouR data generation" />

  <meta name="generator" content="Hugo 0.21" />
  <link rel="canonical" href="/post/marginal-v-conditional/" />
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="ouR data generation">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/main.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="/css/pygment_highlights.css" />
  <link rel="stylesheet" href="/css/highlight.min.css" />

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ouR data generation</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="simstudy" href="https://cran.r-project.org/web/packages/simstudy/index.html">simstudy</a>
            </li>
          
        
          
            <li>
              <a title="NYUSOM" href="https://med.nyu.edu/pophealth/department-population-health">NYUSOM</a>
            </li>
          
        
          
            <li>
              <a title="Bio" href="https://med.nyu.edu/faculty/keith-s-goldfeld">Bio</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>When marginal and conditional logistic model estimates diverge</h1>
                
                
                  <span class="post-meta">
  Posted on June 8, 2017
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        <STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 9pt;
    height: 2px;
    padding:0px;
    cellpadding="0";
    cellspacing="0";
    text-align: center;
  }
  th {
    font-family: Arial; 
    font-size: 9pt;
    height: 20px;
    font-weight: bold;
    text-align: center;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>
<p>Say we have an intervention that is assigned at a group or cluster level but the outcome is measured at an individual level (e.g. students in different schools, eyes on different individuals). And, say this outcome is binary; that is, something happens, or it doesn’t. (This is important, because none of this is true if the outcome is continuous and at close to normally distributed.) If we want to measure the <em>effect</em> of the intervention - perhaps the risk difference, risk ratio, or odds ratio - it can really matter if we are interested in the <em>marginal</em> effect or the <em>conditional</em> effect, because there is a good chance they won’t be the same. My aim here is simply to show this difference visually, as well do an exercise in data simulation.</p>
<p>Below we have a series of plots with three distinct elements. The grey lines represent patient-level probabilities within a cluster that are a function of some patient-level characteristic (say age) and a cluster-specific tendency. We can see that in all cases the probabilities increase with age. However, we can see that for a particular age there can be quite a range of probabilities - this is the across-cluster variability. This can be read by going up vertically from the age (x) axis. So in the top plot, at age 0 (say age is normalized by the mean age), the probablities of the outcome across the clusters range from almost 0% to almost 100%.</p>
<p>The black lines represent the probability curve for the average cluster, for which the cluster-level effect is essentially 0. (For other clusters, the cluster-level effects are typically assume to be scattered around 0, or more specifically normally distributed around 0, with some level of unknown variance.) This black line is the <em>conditional</em> probability (conditional on the cluster).</p>
<p>The red line shows the average of the outcome probability across all the clusters at each age. This is the <em>marginal</em> average line. (The is really more conceptual than real, because these drawings assume that the number of individuals per cluster is the same, and that distribution across ages is uniform; the point is not to be real but to show graphically sort of what is going on.)</p>
<p>In the two sets of plots, the top plot represents the probabilities for clusters under the intervention, the middle plot represents the probabilities for clusters under control (you can think of these as potential probabilities if you are familiar with the <em>causal inference</em> framework, but that is a whole other thing), and the bottom plot is the difference between the top two figures, which represents the treatment effects as risk differences.</p>
<p>Now, take a look at the plots. The key thing to notice is that in the first scenario the red (marginal) and black (conditional) lines diverge, whereas in the second scenario, they pretty much overlap. The difference between the two scenarios? Between cluster variation.</p>
<div id="substantial-heterogeneity" class="section level3">
<h3>Substantial heterogeneity</h3>
<p><img src="/post/2017-06-05-when-marginal-and-conditional-logistic-models-provide-divergent-estimates_files/figure-html/plot1gee-1.png" width="432" style="display: block; margin: auto;" /></p>
</div>
<div id="not-so-much-heterogeneity" class="section level2">
<h2>Not so much heterogeneity</h2>
<p><img src="/post/2017-06-05-when-marginal-and-conditional-logistic-models-provide-divergent-estimates_files/figure-html/plot2gee-1.png" width="432" style="display: block; margin: auto;" /></p>
<div id="simulating-data-and-comparing-model-fits" class="section level3">
<h3>Simulating data and comparing model fits</h3>
<p>We can use a simpler set of scenarios (by ignoring any individual-level factors) to see how this variation in variation plays out in estimation. Using <code>simstudy</code> functions to define and generate the data from a random intercept model, we see what happens under two different scenarios. In the first scenario, we introduce large amounts variance across the cluster specific averages - so that <span class="math inline">\(var(\alpha_i)\)</span> is relatively high. In the second, we set <span class="math inline">\(var(\alpha_i)\)</span> close to 0.</p>
<p>This is the simple underlying data generating model:</p>
<p><span class="math display">\[ log\left[\frac{P(Y_i)}{1-P(Y_i)}\right] = \alpha_i + \beta_1*Trt_i\]</span></p>
<p>In the code below, clusters are generated along with cluster-level effects (with either high or low variance) and group assignments (treatment group = 1 for the intervention, 0 otherwise). Individuals are generated within clusters with outcome probabilities that are a function of the cluster specific effect and the cluster’s group assignment. In the last step, individual-level outcomes are generated based on each individual’s outcome probability. All of this was implemented in a single function. After generating the data, I fit a generalized linear mixed effects model (from package <code>lme4</code>) and a generalized estimating equation model (from package <code>gee</code>) to compare the marginal and conditional models.</p>
<pre class="r"><code>library(lme4)
library(gee)
library(gridExtra)
library(simstudy)

genFunc &lt;- function(nClusters, effVar) {
  
  # Define the data definitions for cluster and individual level data
  
  def1 &lt;- defData(varname = &quot;clustEff&quot;, formula = 0, variance = effVar, id = &quot;cID&quot;)
  def1 &lt;- defData(def1, varname = &quot;nInd&quot;, formula = 40, dist = &quot;noZeroPoisson&quot;)
  
  def2 &lt;- defDataAdd(varname = &quot;Y&quot;, formula = &quot;-2 + 2*grp + clustEff&quot;, 
                       dist = &quot;binary&quot;, link = &quot;logit&quot;)
  
  # Generate cluster level data
  
  dtC &lt;- genData(nClusters, def1)
  dtC &lt;- trtAssign(dtC, grpName = &quot;grp&quot;)
  
  # Generate individual level data
  
  dt &lt;- genCluster(dtClust = dtC, cLevelVar = &quot;cID&quot;, numIndsVar = &quot;nInd&quot;, 
                      level1ID = &quot;id&quot;)
  dt &lt;- addColumns(def2, dt)
  
  return(dt)
  
}</code></pre>
</div>
<div id="lots-of-variability" class="section level3">
<h3>Lots of variability</h3>
<pre class="r"><code>set.seed(123)
dt1 &lt;- genFunc(100, 1)

glmerFit1 &lt;- glmer(Y ~ grp + (1 | cID), data = dt1, family=&quot;binomial&quot;)
  
geeFit1 &lt;- gee(Y ~ grp, family = binomial, data = dt1, 
                   corstr = &quot;exchangeable&quot;, id = dt1$cID)</code></pre>
<pre><code>##      Intercept  Grp
## GLMM     -1.88 1.89
## GEE      -1.62 1.63</code></pre>
<p>In this scenario, the marginal model estimate of the average treatment effect (on the log-odds scale) is considerably lower than the true conditional model, 1.63 vs 1.89.</p>
</div>
<div id="very-little-variability" class="section level3">
<h3>Very little variability</h3>
<pre class="r"><code>set.seed(123)
dt2 &lt;- genFunc(100, .05)

glmerFit2 &lt;- glmer(Y ~ grp + (1 | cID), data = dt2, family=&quot;binomial&quot;)

geeFit2 &lt;- gee(Y ~ grp, family = binomial, data = dt2, 
                   corstr = &quot;exchangeable&quot;, id = dt2$cID)</code></pre>
<pre><code>##      Intercept  Grp
## GLMM     -2.01 1.95
## GEE      -2.00 1.94</code></pre>
<p>When the variability across clusters is dramatically reduced, the marginal model estimates are much more in line with the conditional model estiamtes.</p>
</div>
</div>

      </article>

      <ul class="pager blog-pager">
        
          <li class="previous">
            <a href="/post/intro-to-simstudy/" data-toggle="tooltip" data-placement="top" title="It can be easy to explore data generating mechanisms with the simstudy package">&larr; Previous Post</a>
          </li>
        
        
      </ul>

      
        
          <div class="disqus-comments">
            <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'KSG';
    var disqus_identifier = '\/post\/marginal-v-conditional\/';
    var disqus_title = 'When marginal and conditional logistic model estimates diverge';
    var disqus_url = '\/post\/marginal-v-conditional\/';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
          </div>
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:keith.goldfeld@nyumc.org" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="/index.xml" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          Keith Goldfeld
          &nbsp;&bull;&nbsp;
          2017

          
            &nbsp;&bull;&nbsp;
            <a href="/">ouR data generation</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.21</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/main.js"></script>
<script src="/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script>
<script> renderMathInElement(document.body); </script>





  </body>
</html>

