---
title: Modeling the secular trend in a cluster randomized trial using a GAM
author: Package Build
date: '2022-10-11'
slug: []
categories: []
tags:
  - R
  - Cluster randomized trials
type: ''
subtitle: ''
image: ''
draft: 'true'
---

```{r options, echo = FALSE}
options(digits = 3)
```

```{r, message=FALSE}
library(simstudy)
library(ggplot2)
library(data.table)
library(mgcv)
library(lme4)
library(splines)
library(gamm4)
```

$$
Y_{ijk} = 100 + b_{0j} + b_{1jk} - 0.1k^2 + 5A_j
$$

```{r}
def <- defData(varname = "b0", formula = 0, variance = 6)
def <- defData(def, varname = "A", formula = "1;1", dist = "trtAssign")
def <- defData(def, varname = "mu", formula = 0, dist = "nonrandom")
def <- defData(def, varname = "s2", formula = 16, dist = "nonrandom")

defOut <- defDataAdd(varname = "y", 
  formula = "100 + b0 + b1k - 0.1 * k^2 + 5*A", 
  variance = 36)
```

```{r}
set.seed(123)

dd <- genData(48, def, id = "site")
dd <- addPeriods(dd, 20, "site", perName = "k")

dd <- addCorGen(dtOld = dd, idvar = "site", nvars = 20, 
  rho = .7, corstr = "ar1",
  dist = "normal", param1 = "mu", param2 = "s2", cnames = "b1k")

dd <- genCluster(dd, "timeID", numIndsVar = 30, level1ID = "id")
dd <- addColumns(defOut, dd)
```

```{r, fig.width = 7, fig.height=3}
dp <- dd[, .(avg = mean(y)), keyby = .(A, site, k)]

ggplot(data = dp, aes(x = k, y = avg)) +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  ylab("average Y") +
  xlab("period (k)") +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) 
```

### Linear model with cubic spline

$$
Y_{ijl} = \beta_0 + s(k) + \delta A
$$

```{r}
lmfit <- lm(y ~ A + bs(x = k, degree = 3, intercept = TRUE) - 1, data = dd)
```

### Put 3 plots together

```{r, fig.width = 7, fig.height=3}
ddpred <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A)]
ddpred$y <- predict(lmfit, ddpred)

ggplot(data = ddpred, aes(x = k, y = y)) +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) 
```

```{r, fig.width = 8, fig.height = 3}
ddx <- ddpred[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)]
ggplot(data = ddx, aes(x = k, y = y)) +
  geom_jitter(aes(x = k, y = y), data = dd[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)], 
              size = .01, color = "grey75") +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  ylab("average Y") +
  xlab("period (k)") +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) +
  facet_wrap(~site, ncol = 4) 
```

### Mixed effects model with cubic spline

```{r, eval=TRUE}
dd[, normk := (k - min(k))/(max(k) - min(k))]

lmefit <- lmer(y ~ A + ( bs(normk) | site) , data = dd)
```

```{r, fig.width = 7, fig.height=3}
ddpred <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A, normk)]
ddpred$y <- predict(lmefit, ddpred)

ggplot(data = ddpred, aes(x = k, y = y)) +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) 
```

```{r, fig.width = 8, fig.height = 3}
ddx <- ddpred[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)]
ggplot(data = ddx, aes(x = k, y = y)) +
  geom_jitter(aes(x = k, y = y), 
              data = dd[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)], 
              size = .01, color = "grey75") +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  ylab("average Y") +
  xlab("period (k)") +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) +
  facet_wrap(~site, ncol = 4) 
```

### Generalized additive model

```{r}
dd$site <- as.factor(dd$site)

gamfit <- gamm(y ~ A + s(k, site, bs = "fs", k = 5), data = dd, method="REML")
```

```{r, fig.width = 7, fig.height=3}
ddpred <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A)]
ddpred$y <- predict(gamfit$gam, ddpred)

ggplot(data = ddpred, aes(x = k, y = y)) +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) 
```

```{r, fig.width = 8, fig.height = 3}
ddx <- ddpred[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)]
ggplot(data = ddx, aes(x = k, y = y)) +
  geom_jitter(aes(x = k, y = y), 
              data = dd[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)], 
              size = .01, color = "grey75") +
  geom_line(aes(group = site, color = factor(A))) +
  scale_color_manual(values = c("#a53e3e", "#3ea5a5"),
                     guide = guide_legend(reverse = TRUE),
                     labels = c("no treatment", "treatment")) +
  ylab("average Y") +
  xlab("period (k)") +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) +
  facet_wrap(~site, ncol = 4) 
```

```{r}
coef(summary(lmfit))["A", c("Estimate", "Std. Error")]
summary(lmefit)$coefficients["A", c("Estimate", "Std. Error")]
cbind(summary(gamfit$gam)$p.coeff, summary(gamfit$gam)$se)[2,]
```

```{r, fig.width = 8, fig.height=4, echo=FALSE}
ddpred.lm <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A)]
ddpred.lm$y <- predict(lmfit, ddpred.lm)
ddpred.lm$mod <- "lm"

ddpred.lme <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A, normk)]
ddpred.lme$y <- predict(lmefit, ddpred.lme)
ddpred.lme$mod <- "lme"

ddpred.gam <- dd[, .SD[1,] , keyby = .(site, k)][, .(site, k, A)]
ddpred.gam$y <- predict(gamfit$gam, ddpred.gam)
ddpred.gam$mod <- "gam"

ddpred <- rbind(ddpred.lm, ddpred.lme, ddpred.gam, fill = TRUE)

ddpred$mod <- factor(ddpred$mod, levels = c("lm",  "lme", "gam"))

x_sites <- c(3, 6, 8, 22, 1, 41, 28, 35)
ddx <- ddpred[site %in% x_sites]

ggplot(data = ddx, aes(x = k, y = y)) +
  geom_jitter(aes(x = k, y = y), 
              data = dd[site %in% c(3, 6, 8, 22, 1, 41, 28, 35)], 
              size = .01, color = "grey70") +
  geom_line(aes(group = mod, color = mod)) +
  scale_color_manual(values = c("#a53e3e", "#3e72a5",  "#3ea572")) +
  ylab("average Y") +
  xlab("period (k)") +
  theme(panel.grid = element_blank(),
        legend.title = element_blank()) +
  facet_wrap(~site, ncol = 4) 
```
