---
title: 'Same model, better shape: why centering improves MCMC'
author: R Build
date: '2026-04-07'
slug: []
categories: []
tags:
  - R
  - Bayesian analysis
type: ''
subtitle: ''
image: ''
draft: TRUE
---



<p>The <em>Emergency departments leading the transformation of Alzheimer’s and dementia care</em> (ED-LEAD) study, which I have written about in the <a href="https://www.rdatagen.net/post/2024-02-20-ensuring-balance-with-a-cluster-randomized-factorial-design/" target="_blank">past</a>, is approaching the end of its third year. This multifactorial design evaluates three independent, yet potentially synergistic, interventions aimed at improving care for persons living with dementia (PLWD) and their caregivers.</p>
<p>To estimate intervention effects, we are using what I’ve <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/sim.70264" target="_blank">called</a> the <em>HEx-factor model</em>, a Bayesian hierarchical exchangeable factorial model. The original plan was to conduct all analyses using <a href="https://mc-stan.org/" target="_blank"><code>Stan</code></a>. However, we’ve run into a bit of a snafu. Working through the issue led to a solution that is worth sharing.</p>
<!--more-->
<p>The challenge turned out to be computational. Because the <em>ED-LEAD</em> analyses must be conducted within the NIA Data LINKAGE Enclave, we are working in a somewhat restricted software environment, at least with respect to Bayesian data analysis. In particular, we have not been able to install or run <code>Stan</code>, which was our original analytic engine. This forced us to consider alternatives, and we turned to <code>JAGS</code>, which is available in the Linkage environment and well-suited for Bayesian hierarchical modeling.</p>
<p>At first glance, this might seem like a straightforward substitution. Both <code>Stan</code> and <code>JAGS</code> allow us to specify the same likelihood and priors. However, I quickly noticed that the models were not performing as well in <code>JAGS</code> as they had in <code>Stan</code>. It turns out that the samplers used in <code>JAGS</code> are more sensitive to posterior dependence than the Hamiltonian Monte Carlo (HMC) methods implemented in <code>Stan</code>.</p>
<p>I set out to understand and fix the problem, and found that a simple reparameterization made a substantial difference. With this change, the <code>JAGS</code> sampler was able to explore the posterior distribution much more efficiently, yielding results comparable to those obtained with <code>Stan</code>.</p>
<p>To understand why this happens, I ran a series of simple simulations comparing the original and reparameterized versions of a basic two-way factorial model. That is what I present here.</p>
<div id="the-setup" class="section level3">
<h3>The setup</h3>
<p>In models with binary predictors and interactions, centering can have a surprisingly large impact on computation, even though it does not change the underlying model. To see this clearly, I’ll start with a simple two-factor logistic model:
<span class="math display">\[
\text{logit}\big[P(Y=1)\big] = \alpha+ \beta_a A + \beta_b B + \beta_{ab}AB
\]</span>
where <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are binary treatment indicators. I’ll compare this to the algebraically equivalent centered version:
<span class="math display">\[
\text{logit}\big[P(Y=1)\big] = \alpha^*+ \gamma_a A^* + \gamma_b B^* + \gamma_{ab}A^*B^*
\]</span>
where</p>
<p><span class="math display">\[
A^* = A - 0.5, \ \ \ B^* = B - 0.5.
\]</span></p>
<p>The scientific model is unchanged. The question is whether the sampler behaves differently.</p>
</div>
<div id="creating-a-single-data-set" class="section level3">
<h3>Creating a single data set</h3>
<p>Before we get started, we need to load the necessary libraries:</p>
<pre class="r"><code>library(simstudy)
library(data.table)
library(ggplot2)
library(rjags)
library(coda)
library(posterior)
library(broom)
library(gt)

RNGkind(&quot;Mersenne-Twister&quot;, &quot;Inversion&quot;, &quot;Rejection&quot;)
set.seed(824)</code></pre>
<p>Here is the data generation process for a single data set. The outcome <span class="math inline">\(Y\)</span> is generated using the binary parameterization of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>:</p>
<pre class="r"><code>s_gen &lt;- function(n = 2000,
                    alpha = -0.8,
                    beta_a = 0.5,
                    beta_b = 0.9,
                    beta_ab = -0.3) {
  
  def &lt;- 
    defData(varname = &quot;A&quot;, formula = 0.5, dist = &quot;binary&quot;) |&gt;
    defData(varname = &quot;B&quot;, formula = 0.5, dist = &quot;binary&quot;) |&gt;
    defData(varname = &quot;AB&quot;, formula = &quot;A*B&quot;, dist = &quot;nonrandom&quot;) |&gt;
    defData(varname = &quot;A_c&quot;, formula = &quot;A - 0.5&quot;, dist = &quot;nonrandom&quot;) |&gt;
    defData(varname = &quot;B_c&quot;, formula = &quot;B - 0.5&quot;, dist = &quot;nonrandom&quot;) |&gt;
    defData(varname = &quot;AB_c&quot;, formula = &quot;A_c * B_c&quot;, dist = &quot;nonrandom&quot;) |&gt;
    defData(
      varname = &quot;Y&quot;, 
      formula = &quot;..alpha + ..beta_a * A + ..beta_b * B + ..beta_ab * AB&quot;,
      dist = &quot;binary&quot;, link = &quot;logit&quot;
    )
    
  genData(n, def)
  
}

dd &lt;- s_gen()</code></pre>
</div>
<div id="the-two-parameterizations-fit-the-same-model" class="section level3">
<h3>The two parameterizations fit the same model</h3>
<p>First, here is the frequentist check. The fitted probabilities are identical, even though the coefficients differ.</p>
<pre class="r"><code>fit_01 &lt;- glm(Y ~ A * B, data = dd, family = binomial)
fit_c  &lt;- glm(Y ~ A_c * B_c, data = dd, family = binomial)

tidy(fit_01)</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   -1.03     0.0995    -10.4  3.90e-25
## 2 A              0.835    0.135       6.18 6.34e-10
## 3 B              1.14     0.134       8.46 2.73e-17
## 4 A:B           -0.670    0.186      -3.61 3.11e- 4</code></pre>
<pre class="r"><code>tidy(fit_c)</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   -0.212    0.0464     -4.57 4.91e- 6
## 2 A_c            0.501    0.0929      5.39 7.05e- 8
## 3 B_c            0.802    0.0929      8.63 6.07e-18
## 4 A_c:B_c       -0.670    0.186      -3.61 3.11e- 4</code></pre>
<p>With 0/1 coding, the log-odds ratio for <span class="math inline">\(A\)</span> alone (that is, when <span class="math inline">\(B=0\)</span>) is simply
<span class="math display">\[
\begin{align*}
\text{lOR}_a(B=0) &amp;= (\alpha + \beta_a \cdot 1 + \beta_b \cdot 0 + \beta_{ab} \cdot 0) -(\alpha + \beta_a \cdot 0 + \beta_b \cdot 0 + \beta_{ab} \cdot 0) \\
&amp; = \beta_a
\end{align*}
\]</span>
Analogously, the log-odds ratio for <span class="math inline">\(B\)</span> alone is <span class="math inline">\(\beta_b\)</span>. And if we want to compare the combination of both <span class="math inline">\(A=1\)</span> and <span class="math inline">\(B=1\)</span> to the case where neither is activated, then
<span class="math display">\[
\begin{align*}
\text{lOR}_{ab} &amp;= (\alpha + \beta_a \cdot 1 + \beta_b \cdot 1 + \beta_{ab} \cdot 1) \\
&amp;\quad -
(\alpha + \beta_a \cdot 0 + \beta_b \cdot 0 + \beta_{ab} \cdot 0) \\
&amp;= \beta_a + \beta_b + \beta_{ab}
\end{align*}
\]</span>
If instead we center the predictors, defining <span class="math inline">\(A^* = A - 0.5\)</span> and <span class="math inline">\(B^* = B - 0.5\)</span>, then the log-odds ratio of exposure to <span class="math inline">\(A\)</span> without exposure to <span class="math inline">\(B\)</span> relative to exposure to neither is
<span class="math display">\[
\begin{align*}
\text{lOR}_a(B=0)
&amp;=
(\alpha^* + \gamma_a(0.5) + \gamma_b(-0.5) + \gamma_{ab}(0.5)(-0.5)) \\
&amp;\quad -
(\alpha^* + \gamma_a(-0.5) + \gamma_b(-0.5) + \gamma_{ab}(-0.5)(-0.5)) \\
&amp;=
(\alpha^* + 0.5\gamma_a - 0.5\gamma_b - 0.25\gamma_{ab}) \\
&amp;\quad -
(\alpha^* - 0.5\gamma_a - 0.5\gamma_b + 0.25\gamma_{ab}) \\
&amp;=
\gamma_a - 0.5\gamma_{ab}.
\end{align*}
\]</span>
Using the same logic we can show that
<span class="math display">\[
\text{lOR}_{b} = \gamma_{b} - 0.5 \gamma_{ab}
\]</span>
and
<span class="math display">\[
\text{lOR}_{ab} = \gamma_a + \gamma_b.
\]</span>
<!-- $$ -->
<!-- \begin{align*} -->
<!-- \text{lOR}_{ab} &= (\alpha^* + \gamma_a(0.5) + \gamma_b(0.5) + \gamma_{ab}(0.5) (0.5)) -  (\alpha^* + \gamma_a(-0.5) + \gamma_b(-0.5) + \gamma_{ab}(-0.5)(-0.5))\\ -->
<!--  &= (\alpha^* + \gamma_a * 0.5 + \gamma_b * 0.5 + \gamma_{ab} * 0.25) -  (\alpha^* - \gamma_a * 0.5 - \gamma_b * 0.5 + \gamma_{ab} * 0.25)\\ -->
<!-- & = \gamma_a + \gamma_b -->
<!-- \end{align*} -->
<!-- $$ -->
From the 0/1-coded model, <span class="math inline">\(\text{lOR}_a = 0.835\)</span>, <span class="math inline">\(\text{lOR}_b = 1.14\)</span>, and <span class="math inline">\(\text{lOR}_{ab} = 0.835 + 1.14 - 0.67 = 1.305.\)</span></p>
<p>From the centered model,
<span class="math display">\[
\text{lOR}_a = 0.501 + 0.5*0.670 = 0.836
\]</span>
<span class="math display">\[
\text{lOR}_b = 0.802 + 0.5*0.670 = 1.137
\]</span>
<span class="math display">\[
\text{lOR}_{ab} = 0.501 + 0.802 = 1.303
\]</span>
So the coefficients themselves change under centering, but the underlying treatment contrasts do not.</p>
</div>
<div id="bayesian-models-using-jags" class="section level3">
<h3>Bayesian models using JAGS</h3>
<p>The model we are fitting is a simple logistic regression with an interaction term:</p>
<p><span class="math display">\[
\begin{align*}
Y_i &amp;\sim \text{Bernoulli}(p_i), \\
\text{logit}(p_i)
&amp;= \alpha + \beta_a A_i + \beta_b B_i + \beta_{ab} A_i B_i,
\end{align*}
\]</span>
Here are the prior distribution assumptions, using variance-based notation to align with JAGS, which parameterizes normal distributions in terms of precision
<span class="math display">\[
\begin{align*}
\alpha &amp;\sim \mathcal{N}(0, 0.25^{-1}), \\
\beta_a &amp;\sim \mathcal{N}(0, 0.25^{-1}), \\
\beta_b &amp;\sim \mathcal{N}(0, 0.25^{-1}), \\
\beta_{ab} &amp;\sim \mathcal{N}(0, 25^{-1}).
\end{align*}
\]</span>
The centered model is similar, except that we replace the coefficients with <span class="math inline">\(\alpha^*\)</span> as well as <span class="math inline">\(\gamma_a\)</span>, <span class="math inline">\(\gamma_b\)</span>, <span class="math inline">\(\gamma_{ab}\)</span>, and define the predictors in terms of centered versions of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. This reparameterization does not change the model itself, but it does change how the coefficients relate to the underlying treatment contrasts.</p>
<pre class="r"><code>model_01 &lt;- &quot;
model {
  for (i in 1:N) {
    Y[i] ~ dbern(p[i])
    logit(p[i]) &lt;- alpha + beta_a * A[i] + beta_b * B[i] + beta_ab * AB[i]
  }
  
  alpha   ~ dnorm(0, 0.25)
  beta_a  ~ dnorm(0, 0.25)
  beta_b  ~ dnorm(0, 0.25)
  beta_ab ~ dnorm(0, 25)
}
&quot;

model_c &lt;- &quot;
model {
  for (i in 1:N) {
    Y[i] ~ dbern(p[i])
    logit(p[i]) &lt;- alpha + gamma_a * A_c[i] + gamma_b * B_c[i] + gamma_ab * AB_c[i]
  }
  
  alpha   ~ dnorm(0, 0.25)
  gamma_a  ~ dnorm(0, 0.25)
  gamma_b  ~ dnorm(0, 0.25)
  gamma_ab ~ dnorm(0, 25)
}
&quot;</code></pre>
</div>
<div id="fit-both-models-to-one-dataset" class="section level3">
<h3>Fit both models to one dataset</h3>
<p>The function <code>fit_jags</code> fits one of the two models just described:</p>
<pre class="r"><code>fit_jags &lt;- function(dat, model_string, centered = FALSE,
                     n_chains = 3, burn = 2000, n_iter = 5000) {
  
  # jdat &lt;- as.list(dat[, .(Y, A, B, AB, A_c, B_c, AB_c)])
  if (centered) {
    jdat &lt;- as.list(dat[, .(Y, A_c, B_c, AB_c)])
    vars &lt;- c(&quot;alpha&quot;, &quot;gamma_a&quot;, &quot;gamma_b&quot;, &quot;gamma_ab&quot;)
  } else {
    jdat &lt;- as.list(dat[, .(Y, A, B, AB)])
    vars &lt;- c(&quot;alpha&quot;, &quot;beta_a&quot;, &quot;beta_b&quot;, &quot;beta_ab&quot;)
  }
  jdat$N &lt;- nrow(dat)
  
  mod &lt;- jags.model(
    textConnection(model_string),
    data = jdat,
    n.chains = n_chains,
    quiet = TRUE
  )
  
  update(mod, burn, progress.bar = &quot;none&quot;)
  
  samp &lt;- coda.samples(
    mod,
    variable.names = vars,
    n.iter = n_iter,
    progress.bar = &quot;none&quot;
  )
  
  samp
}</code></pre>
<p>Now, we can fit the models, collect the diagnostic data, and take a look at the results:</p>
<pre class="r"><code>samp_01 &lt;- fit_jags(dd, model_01, centered = FALSE)
samp_c  &lt;- fit_jags(dd, model_c, centered = TRUE)

diag_tbl &lt;- function(samp, model_name) {
  post &lt;- as_draws_df(samp)
  summ &lt;- summarise_draws(post)
  out &lt;- as.data.table(summ)
  out[, model := model_name]
  out[]
}

diag_01 &lt;- diag_tbl(samp_01, &quot;0/1-coded&quot;)
diag_c  &lt;- diag_tbl(samp_c, &quot;centered&quot;)</code></pre>
<div id="bxfxwqtyqe" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#bxfxwqtyqe table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#bxfxwqtyqe thead, #bxfxwqtyqe tbody, #bxfxwqtyqe tfoot, #bxfxwqtyqe tr, #bxfxwqtyqe td, #bxfxwqtyqe th {
  border-style: none;
}

#bxfxwqtyqe p {
  margin: 0;
  padding: 0;
}

#bxfxwqtyqe .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 15px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bxfxwqtyqe .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#bxfxwqtyqe .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bxfxwqtyqe .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bxfxwqtyqe .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bxfxwqtyqe .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxfxwqtyqe .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bxfxwqtyqe .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bxfxwqtyqe .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bxfxwqtyqe .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bxfxwqtyqe .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bxfxwqtyqe .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bxfxwqtyqe .gt_spanner_row {
  border-bottom-style: hidden;
}

#bxfxwqtyqe .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#bxfxwqtyqe .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bxfxwqtyqe .gt_from_md > :first-child {
  margin-top: 0;
}

#bxfxwqtyqe .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bxfxwqtyqe .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bxfxwqtyqe .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bxfxwqtyqe .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bxfxwqtyqe .gt_row_group_first td {
  border-top-width: 2px;
}

#bxfxwqtyqe .gt_row_group_first th {
  border-top-width: 2px;
}

#bxfxwqtyqe .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxfxwqtyqe .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bxfxwqtyqe .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bxfxwqtyqe .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxfxwqtyqe .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxfxwqtyqe .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bxfxwqtyqe .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#bxfxwqtyqe .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bxfxwqtyqe .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxfxwqtyqe .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bxfxwqtyqe .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxfxwqtyqe .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bxfxwqtyqe .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxfxwqtyqe .gt_left {
  text-align: left;
}

#bxfxwqtyqe .gt_center {
  text-align: center;
}

#bxfxwqtyqe .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bxfxwqtyqe .gt_font_normal {
  font-weight: normal;
}

#bxfxwqtyqe .gt_font_bold {
  font-weight: bold;
}

#bxfxwqtyqe .gt_font_italic {
  font-style: italic;
}

#bxfxwqtyqe .gt_super {
  font-size: 65%;
}

#bxfxwqtyqe .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#bxfxwqtyqe .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bxfxwqtyqe .gt_indent_1 {
  text-indent: 5px;
}

#bxfxwqtyqe .gt_indent_2 {
  text-indent: 10px;
}

#bxfxwqtyqe .gt_indent_3 {
  text-indent: 15px;
}

#bxfxwqtyqe .gt_indent_4 {
  text-indent: 20px;
}

#bxfxwqtyqe .gt_indent_5 {
  text-indent: 25px;
}

#bxfxwqtyqe .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#bxfxwqtyqe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">Parameter</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mean">Mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="median">Median</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="sd">SD</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mad">MAD</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="q5">5th %tile</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="q95">95th %tile</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="rhat">R-hat</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="ess_bulk">ESS (bulk)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="ess_tail">ESS (tail)</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="10" class="gt_group_heading" style="font-weight: bold;" scope="colgroup" id="0/1-coded">0/1-coded</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="0/1-coded  variable" class="gt_row gt_left">alpha</td>
<td headers="0/1-coded  mean" class="gt_row gt_right">-0.937</td>
<td headers="0/1-coded  median" class="gt_row gt_right">-0.937</td>
<td headers="0/1-coded  sd" class="gt_row gt_right">0.092</td>
<td headers="0/1-coded  mad" class="gt_row gt_right">0.093</td>
<td headers="0/1-coded  q5" class="gt_row gt_right">-1.088</td>
<td headers="0/1-coded  q95" class="gt_row gt_right">-0.786</td>
<td headers="0/1-coded  rhat" class="gt_row gt_right">1.001</td>
<td headers="0/1-coded  ess_bulk" class="gt_row gt_right">1359.836</td>
<td headers="0/1-coded  ess_tail" class="gt_row gt_right">2862.560</td></tr>
    <tr><td headers="0/1-coded  variable" class="gt_row gt_left">beta_a</td>
<td headers="0/1-coded  mean" class="gt_row gt_right">0.665</td>
<td headers="0/1-coded  median" class="gt_row gt_right">0.665</td>
<td headers="0/1-coded  sd" class="gt_row gt_right">0.117</td>
<td headers="0/1-coded  mad" class="gt_row gt_right">0.118</td>
<td headers="0/1-coded  q5" class="gt_row gt_right">0.472</td>
<td headers="0/1-coded  q95" class="gt_row gt_right">0.855</td>
<td headers="0/1-coded  rhat" class="gt_row gt_right">1.001</td>
<td headers="0/1-coded  ess_bulk" class="gt_row gt_right">1612.670</td>
<td headers="0/1-coded  ess_tail" class="gt_row gt_right">3084.048</td></tr>
    <tr><td headers="0/1-coded  variable" class="gt_row gt_left">beta_ab</td>
<td headers="0/1-coded  mean" class="gt_row gt_right">-0.352</td>
<td headers="0/1-coded  median" class="gt_row gt_right">-0.352</td>
<td headers="0/1-coded  sd" class="gt_row gt_right">0.137</td>
<td headers="0/1-coded  mad" class="gt_row gt_right">0.139</td>
<td headers="0/1-coded  q5" class="gt_row gt_right">-0.579</td>
<td headers="0/1-coded  q95" class="gt_row gt_right">-0.128</td>
<td headers="0/1-coded  rhat" class="gt_row gt_right">1.001</td>
<td headers="0/1-coded  ess_bulk" class="gt_row gt_right">1699.870</td>
<td headers="0/1-coded  ess_tail" class="gt_row gt_right">3617.854</td></tr>
    <tr><td headers="0/1-coded  variable" class="gt_row gt_left">beta_b</td>
<td headers="0/1-coded  mean" class="gt_row gt_right">0.969</td>
<td headers="0/1-coded  median" class="gt_row gt_right">0.968</td>
<td headers="0/1-coded  sd" class="gt_row gt_right">0.118</td>
<td headers="0/1-coded  mad" class="gt_row gt_right">0.119</td>
<td headers="0/1-coded  q5" class="gt_row gt_right">0.777</td>
<td headers="0/1-coded  q95" class="gt_row gt_right">1.164</td>
<td headers="0/1-coded  rhat" class="gt_row gt_right">1.001</td>
<td headers="0/1-coded  ess_bulk" class="gt_row gt_right">1430.007</td>
<td headers="0/1-coded  ess_tail" class="gt_row gt_right">3298.993</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="10" class="gt_group_heading" style="font-weight: bold;" scope="colgroup" id="centered">centered</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="centered  variable" class="gt_row gt_left">alpha</td>
<td headers="centered  mean" class="gt_row gt_right">-0.210</td>
<td headers="centered  median" class="gt_row gt_right">-0.210</td>
<td headers="centered  sd" class="gt_row gt_right">0.047</td>
<td headers="centered  mad" class="gt_row gt_right">0.047</td>
<td headers="centered  q5" class="gt_row gt_right">-0.285</td>
<td headers="centered  q95" class="gt_row gt_right">-0.133</td>
<td headers="centered  rhat" class="gt_row gt_right">1.000</td>
<td headers="centered  ess_bulk" class="gt_row gt_right">9278.897</td>
<td headers="centered  ess_tail" class="gt_row gt_right">9114.590</td></tr>
    <tr><td headers="centered  variable" class="gt_row gt_left">gamma_a</td>
<td headers="centered  mean" class="gt_row gt_right">0.492</td>
<td headers="centered  median" class="gt_row gt_right">0.492</td>
<td headers="centered  sd" class="gt_row gt_right">0.094</td>
<td headers="centered  mad" class="gt_row gt_right">0.094</td>
<td headers="centered  q5" class="gt_row gt_right">0.337</td>
<td headers="centered  q95" class="gt_row gt_right">0.647</td>
<td headers="centered  rhat" class="gt_row gt_right">1.000</td>
<td headers="centered  ess_bulk" class="gt_row gt_right">9316.962</td>
<td headers="centered  ess_tail" class="gt_row gt_right">8853.810</td></tr>
    <tr><td headers="centered  variable" class="gt_row gt_left">gamma_ab</td>
<td headers="centered  mean" class="gt_row gt_right">-0.361</td>
<td headers="centered  median" class="gt_row gt_right">-0.362</td>
<td headers="centered  sd" class="gt_row gt_right">0.135</td>
<td headers="centered  mad" class="gt_row gt_right">0.134</td>
<td headers="centered  q5" class="gt_row gt_right">-0.582</td>
<td headers="centered  q95" class="gt_row gt_right">-0.140</td>
<td headers="centered  rhat" class="gt_row gt_right">1.000</td>
<td headers="centered  ess_bulk" class="gt_row gt_right">9167.199</td>
<td headers="centered  ess_tail" class="gt_row gt_right">9311.161</td></tr>
    <tr><td headers="centered  variable" class="gt_row gt_left">gamma_b</td>
<td headers="centered  mean" class="gt_row gt_right">0.795</td>
<td headers="centered  median" class="gt_row gt_right">0.795</td>
<td headers="centered  sd" class="gt_row gt_right">0.093</td>
<td headers="centered  mad" class="gt_row gt_right">0.095</td>
<td headers="centered  q5" class="gt_row gt_right">0.642</td>
<td headers="centered  q95" class="gt_row gt_right">0.946</td>
<td headers="centered  rhat" class="gt_row gt_right">1.001</td>
<td headers="centered  ess_bulk" class="gt_row gt_right">8969.964</td>
<td headers="centered  ess_tail" class="gt_row gt_right">8821.275</td></tr>
  </tbody>
  
</table>
</div>
<p>There are a few things to notice here. First, the Bayesian estimates for both the 0/1-coded and centered data are closer to zero than the GLM estimates above. The shrinkage is particularly large for the interaction term, because we placed much more restrictive priors on <span class="math inline">\(\beta_{ab}\)</span> and <span class="math inline">\(\gamma_{ab}\)</span>. This is exactly what we would expect: the prior is pulling the interaction toward zero, and that influence shows up clearly in the posterior summaries.</p>
<p>Second, if we compare the two parameterizations, we see that the R-hat—essentially a measure of whether the chains have converged to the same distribution—is slightly lower for the centered data. There isn’t much to make of the difference here (both are very close to 1), but it does suggest slightly more stable behavior.</p>
<p>The biggest impact is on the bulk effective sample size (ESS), which reflects how much independent information the chains contain after accounting for autocorrelation. Even though we ran the same number of iterations, the centered model yields far larger ESS values, indicating much better mixing. In other words, the sampler is exploring the posterior much more efficiently under the centered parameterization, and in this case the improvement is quite dramatic. Importantly, these differences have nothing to do with the models themselves since the likelihood is unchanged. Rather, it reflects how easy it is for the sampler to navigate the posterior surface when the data are centered.</p>
<p>A comparison of the trace plots reinforces the stability that centering the data provides. The traces for the 0/1-coded data are a bit more irregular, suggesting less efficient exploration of the posterior. In contrast, the centered parameterization produces tighter, more stable traces with less autocorrelation, indicating that the chains are mixing more effectively. This aligns with the much larger effective sample sizes observed for the centered model.</p>
<p><img src="code_and_data/trace_plot.png" /></p>
<pre class="r"><code>get_lor_summary &lt;- function(samp, model_name) {
  dt &lt;- as.data.table(as_draws_df(samp))
  
  if (model_name == &quot;0/1-coded&quot;) {
    dt[, lOR_A := beta_a]
    dt[, lOR_B := beta_b]
    dt[, lOR_AB := beta_a + beta_b + beta_ab]
  } else {
    dt[, lOR_A := gamma_a - 0.5 * gamma_ab]
    dt[, lOR_B := gamma_b - 0.5 * gamma_ab]
    dt[, lOR_AB := gamma_a + gamma_b]
  }
  
  dt[, .(
    mean_A = mean(lOR_A),
    mean_B = mean(lOR_B),
    mean_AB = mean(lOR_AB),
    sd_A = sd(lOR_A),
    sd_B = sd(lOR_B),
    sd_AB = sd(lOR_AB)
  )]
}

lor_01 &lt;- get_lor_summary(samp_01, &quot;0/1-coded&quot;)
lor_c  &lt;- get_lor_summary(samp_c,  &quot;centered&quot;)</code></pre>
<div id="xwzeufbwmd" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xwzeufbwmd table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xwzeufbwmd thead, #xwzeufbwmd tbody, #xwzeufbwmd tfoot, #xwzeufbwmd tr, #xwzeufbwmd td, #xwzeufbwmd th {
  border-style: none;
}

#xwzeufbwmd p {
  margin: 0;
  padding: 0;
}

#xwzeufbwmd .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xwzeufbwmd .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xwzeufbwmd .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xwzeufbwmd .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xwzeufbwmd .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xwzeufbwmd .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xwzeufbwmd .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xwzeufbwmd .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xwzeufbwmd .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xwzeufbwmd .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xwzeufbwmd .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xwzeufbwmd .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xwzeufbwmd .gt_spanner_row {
  border-bottom-style: hidden;
}

#xwzeufbwmd .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xwzeufbwmd .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xwzeufbwmd .gt_from_md > :first-child {
  margin-top: 0;
}

#xwzeufbwmd .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xwzeufbwmd .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xwzeufbwmd .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xwzeufbwmd .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xwzeufbwmd .gt_row_group_first td {
  border-top-width: 2px;
}

#xwzeufbwmd .gt_row_group_first th {
  border-top-width: 2px;
}

#xwzeufbwmd .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xwzeufbwmd .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xwzeufbwmd .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xwzeufbwmd .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xwzeufbwmd .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xwzeufbwmd .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xwzeufbwmd .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xwzeufbwmd .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xwzeufbwmd .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xwzeufbwmd .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xwzeufbwmd .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xwzeufbwmd .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xwzeufbwmd .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xwzeufbwmd .gt_left {
  text-align: left;
}

#xwzeufbwmd .gt_center {
  text-align: center;
}

#xwzeufbwmd .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xwzeufbwmd .gt_font_normal {
  font-weight: normal;
}

#xwzeufbwmd .gt_font_bold {
  font-weight: bold;
}

#xwzeufbwmd .gt_font_italic {
  font-style: italic;
}

#xwzeufbwmd .gt_super {
  font-size: 65%;
}

#xwzeufbwmd .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xwzeufbwmd .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xwzeufbwmd .gt_indent_1 {
  text-indent: 5px;
}

#xwzeufbwmd .gt_indent_2 {
  text-indent: 10px;
}

#xwzeufbwmd .gt_indent_3 {
  text-indent: 15px;
}

#xwzeufbwmd .gt_indent_4 {
  text-indent: 20px;
}

#xwzeufbwmd .gt_indent_5 {
  text-indent: 25px;
}

#xwzeufbwmd .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#xwzeufbwmd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="model"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="A">log OR A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="B">log OR B</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="AB">log OR AB</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="model" class="gt_row gt_left">0/1-coded</td>
<td headers="A" class="gt_row gt_center">0.672 (0.115)</td>
<td headers="B" class="gt_row gt_center">0.973 (0.116)</td>
<td headers="AB" class="gt_row gt_center">1.286 (0.132)</td></tr>
    <tr><td headers="model" class="gt_row gt_left">centered</td>
<td headers="A" class="gt_row gt_center">0.672 (0.116)</td>
<td headers="B" class="gt_row gt_center">0.975 (0.117)</td>
<td headers="AB" class="gt_row gt_center">1.288 (0.134)</td></tr>
  </tbody>
  
</table>
</div>
</div>
<div id="a-larger-simulation-experiment" class="section level3">
<h3>A larger simulation experiment</h3>
<p>A single data set can be misleading. So next I’ll repeat this 500 times and compare the two parameterizations across simulations. Each iteration, I generate a data set with 2000 observations, I fit each model—the one with 0/1-coding and the other with centered coding—using <code>JAGS</code>, and collecting summary data of the posteriors from each model <code>JAGS</code>: mean, median, standard deviation, median absolute deviation, 5th percentile, 95th percentile, R-hat, bulk ESS, and tail ESS.</p>
<pre class="r"><code>one_run &lt;- function(
  n = 2000,
  truth = c(alpha = -0.8, beta_a = 0.5, beta_b = 0.9, beta_ab = -0.3),
  n_chains = 3,
  burn = 1000,
  n_iter = 3000
) {
  
  dd &lt;- s_gen(
    n = n,
    alpha = truth[&quot;alpha&quot;],
    beta_a = truth[&quot;beta_a&quot;],
    beta_b = truth[&quot;beta_b&quot;],
    beta_ab = truth[&quot;beta_ab&quot;]
  )
  
  samp_01 &lt;- fit_jags(
    dd, model_01, centered = FALSE, 
    n_chains = n_chains, burn = burn, n_iter = n_iter
  )
  
  samp_c &lt;- fit_jags(
    dd, model_c, centered = TRUE, 
    n_chains = n_chains, burn = burn, n_iter = n_iter)
  
  get_metrics &lt;- function(samp, model_name) {
    post &lt;- as_draws_df(samp)
    summ &lt;- as.data.table(summarise_draws(post))
    summ[, model := model_name]
    summ[]
  }
  
  out &lt;- rbindlist(list(
    get_metrics(samp_01, &quot;0/1-coded&quot;),
    get_metrics(samp_c,  &quot;centered&quot;)
  ))
  
  out[]
}

nsim &lt;- 500

sim_res &lt;- rbindlist(mclapply(seq_len(nsim), function(i) {
  out &lt;- one_run()
  out[, sim := i]
  out[]
}, mc.cores = 5))</code></pre>
<p>Earlier we saw for a single data set, there was not much difference in R-hat (essentially a measure of whether the chains have converged to the same distribution) between the two models. However, over repeated data sets, a more interesting picture emerges. The figure below shows that while R-hat for the 0/1-coding model is quite low, R-hat for the centered-coding is lower still, and much more consistent, suggesting that mixing is stronger in the centered model.</p>
<p><img src="code_and_data/plot_rhat_V1.png" alt="" width="75%" /></p>
<p>The next figure confirms what we saw earlier. This shows the distribution of ratios of bulk ESS in the centered model compared to the 0/1-coding model. If the two models had the same effective sample size, we would expect those ratios to cluster near one. However, they are all mostly greater than five, confirming what we saw for the individual data set.</p>
<p><img src="code_and_data/plot_ess_V1.png" alt="" width="75%" /></p>
<p>The key issue is posterior dependence among parameters: when parameters are highly correlated, the sampler must explore long, narrow regions in the posterior, which slows mixing.</p>
</div>
<div id="understanding-what-is-driving-the-performance" class="section level3">
<h3>Understanding what is driving the performance</h3>
<p>To better understand this, we can look directly at the dependence structure of the posterior draws. Correlation plots help explain what is driving these differences in performance. Under the 0/1-coded parameterization, the posterior exhibits strong dependence among parameters. Several pairs of coefficients show substantial correlations, reflecting the fact that different combinations of parameters can produce similar fitted values. In geometric terms, the joint posterior has an elongated, highly correlated structure. This is evident in the pairwise scatter plots, where draws fall along narrow, tilted bands rather than forming roughly circular clouds.</p>
<p><img src="code_and_data/plot_cor_01_V1.png" alt="" width="75%" /></p>
<p>This geometry makes life difficult for the sampler. Exploring such a narrow region requires many small, correlated steps, which leads to high autocorrelation and, ultimately, low effective sample sizes.</p>
<p>In contrast, the centered parameterization produces a posterior that is nearly uncorrelated. The coefficients capture more distinct aspects of the model, and the resulting posterior is much more spherical. This greatly simplifies the exploration of the parameter space, allowing the sampler to move more freely.</p>
<p><img src="code_and_data/plot_cor_c_V1.png" alt="" width="75%" /></p>
<p>The key point is that centering does not change the model or the scientific conclusions. It changes the geometry of the posterior distribution, and that change can have a dramatic impact on computational performance. In effect, centering makes the parameters closer to orthogonal in the posterior, reducing interference among them and improving both statistical and computational behavior.</p>
<p>In the ED-LEAD study, where we are fitting hierarchical factorial models with multiple intervention components, this shift in parameterization is critical. Centering the treatment indicators leads to more stable estimation and far more efficient sampling, which is particularly important given our reliance on <code>JAGS</code>. Unlike Hamiltonian Monte Carlo (as implemented in <code>Stan</code>), which can handle correlated posteriors more effectively, the Gibbs and Metropolis-based updates used by <code>JAGS</code> are much more sensitive to posterior dependence. Improving the geometry of the posterior is therefore essential for good performance in this setting.</p>
<p>
<p><small><font color="darkkhaki">
Support:</p>
This work was supported in part by the National Institute on Aging (NIA) of the National Institutes of Health under Award Number U19AG078105, which funds the <em>Emergency departments leading the transformation of Alzheimer’s and dementia care</em> (ED-LEAD) study. The author, the leader of the Statistics Analysis Core, was the sole writer of this blog post and has no conflicts. The content is solely the responsibility of the author and does not necessarily represent the official views of the National Institutes of Health.
</font></small>
</p>
</div>
